[View in Colaboratory](https://colab.research.google.com/github/rohithmanjunath/mlblr_assignment2/blob/master/Manjunath_D_Batch6_Assignment2b.ipynb)

In [8]:
import numpy as np

#sigmoid
def sigmoid(x):
  return (1/(1+np.exp(-x)))

def derivatives_sigmoid(x):
  return (x*(1-x))
  
def random_init(size, low=0.0, high=1.0):
  return np.random.uniform(size=size, low=low, high=high)

learning_rate = 0.1

#Step 0
X = np.array([[1,0,1,0],[1,0,1,1],[0,1,0,1]])
y = np.array([[1],[1],[0]])

#Step 1
wh = random_init((4,3))
bh = random_init((1,3))
wout = random_init((3,1))
bout = random_init((1,1))

print("Input, X:\n")
print(X)
print("Target Output, y:\n")
print(y)
print("Hidden layer weight, wh:\n")
print(wh)
print("Hidden layer bias, bh:\n")
print(bh)
print("Output layer weight, wout:\n")
print(wout)
print("Hidden layer bias, bout:\n")
print(bout)



Input, X:

[[1 0 1 0]
 [1 0 1 1]
 [0 1 0 1]]
Target Output, y:

[[1]
 [1]
 [0]]
Hidden layer weight, wh:

[[0.54550004 0.82370192 0.08994699]
 [0.96174297 0.301314   0.53212312]
 [0.31813994 0.1606409  0.89742398]
 [0.08382366 0.47725419 0.78025754]]
Hidden layer bias, bh:

[[0.24428054 0.67119878 0.12892726]]
Output layer weight, wout:

[[0.34132111]
 [0.84090067]
 [0.87431088]]
Hidden layer bias, bout:

[[0.52671621]]


In [9]:
#Step 2
hidden_layer_input = np.dot(X, wh) + bh
print("Hidden layer input, hidden_layer_input:\n")
print(hidden_layer_input)

Hidden layer input, hidden_layer_input:

[[1.10792052 1.65554159 1.11629823]
 [1.19174418 2.13279578 1.89655577]
 [1.28984717 1.44976696 1.44130792]]


In [10]:
#Step 3
hiddenlayer_activations = sigmoid(hidden_layer_input)
print("Hidden layer activation, hiddenlayer_activations:\n")
print(hiddenlayer_activations)

Hidden layer activation, hiddenlayer_activations:

[[0.75174123 0.83963861 0.75330143]
 [0.76705286 0.89405013 0.86950121]
 [0.78412132 0.80996257 0.80865711]]
