[View in Colaboratory](https://colab.research.google.com/github/rohithmanjunath/mlblr_assignment2/blob/master/Manjunath_D_Batch6_Assignment2b.ipynb)

In [19]:
import numpy as np

#sigmoid
def sigmoid(x):
  return (1/(1+np.exp(-x)))

def derivatives_sigmoid(x):
  return (x*(1-x))
  
def random_init(size, low=0.0, high=1.0):
  return np.random.uniform(size=size, low=low, high=high)

learning_rate = 0.1

#Step 0
X = np.array([[1,0,1,0],[1,0,1,1],[0,1,0,1]])
y = np.array([[1],[1],[0]])

#Step 1
wh = random_init((4,3))
bh = random_init((1,3))
wout = random_init((3,1))
bout = random_init((1,1))

print("Input, X:\n")
print(X)
print("Target Output, y:\n")
print(y)
print("Hidden layer weight, wh:\n")
print(wh)
print("Hidden layer bias, bh:\n")
print(bh)
print("Output layer weight, wout:\n")
print(wout)
print("Hidden layer bias, bout:\n")
print(bout)



Input, X:

[[1 0 1 0]
 [1 0 1 1]
 [0 1 0 1]]
Target Output, y:

[[1]
 [1]
 [0]]
Hidden layer weight, wh:

[[0.59694117 0.7701998  0.81848355]
 [0.19574107 0.73111538 0.6055217 ]
 [0.72647895 0.15408443 0.36265119]
 [0.6770187  0.92189296 0.31618089]]
Hidden layer bias, bh:

[[0.9726875  0.14202168 0.60482676]]
Output layer weight, wout:

[[0.30297908]
 [0.80922413]
 [0.5428705 ]]
Hidden layer bias, bout:

[[0.69546112]]


In [20]:
#Step 2
hidden_layer_input = np.dot(X, wh) + bh
print("Hidden layer input, hidden_layer_input:\n")
print(hidden_layer_input)

Hidden layer input, hidden_layer_input:

[[2.29610761 1.06630591 1.7859615 ]
 [2.97312632 1.98819887 2.10214238]
 [1.84544727 1.79503002 1.52652934]]


In [21]:
#Step 3
hiddenlayer_activations = sigmoid(hidden_layer_input)
print("Hidden layer activation, hiddenlayer_activations:\n")
print(hiddenlayer_activations)

Hidden layer activation, hiddenlayer_activations:

[[0.90855416 0.74389377 0.85643143]
 [0.95134519 0.87955246 0.89111123]
 [0.86359167 0.85754287 0.82149795]]


In [22]:
#Step 4
output_layer_input = np.dot(hiddenlayer_activations, wout ) + bout
output = sigmoid(output_layer_input)
print("Output layer input matrix, output_layer_input:\n")
print(output_layer_input)
print("Output layer output matrix, output:\n")
print(output)

Output layer input matrix, output_layer_input:

[[2.03764217]
 [2.17921188]
 [2.09702271]]
Output layer output matrix, output:

[[0.88469296]
 [0.89836714]
 [0.89061347]]


In [24]:
#Step 5
E = y-output
print("Error in training output, E:\n")
print(E)

Error in training output, E:

[[ 0.11530704]
 [ 0.10163286]
 [-0.89061347]]


In [26]:
#Step 6
Slope_output_layer= derivatives_sigmoid(output)
Slope_hidden_layer = derivatives_sigmoid(hiddenlayer_activations)
print("Slope of output layer's output, Slope_output_layer:\n")
print(Slope_output_layer)
print("Slope of hidden layer's output , Slope_hidden_layer:\n")
print(Slope_hidden_layer)

Slope of output layer's output, Slope_output_layer:

[[0.10201133]
 [0.09130362]
 [0.09742112]]
Slope of hidden layer's output , Slope_hidden_layer:

[[0.0830835  0.19051583 0.12295664]
 [0.04628752 0.10593993 0.097032  ]
 [0.1178011  0.1221631  0.14663907]]


In [27]:
#Step 7
d_output = E * Slope_output_layer * learning_rate
print("Delta of output layer, d_output:\n")
print(d_output)

Delta of output layer, d_output:

[[ 0.00117626]
 [ 0.00092794]
 [-0.00867646]]


In [29]:
#Step 8
Error_at_hidden_layer = np.dot(d_output, wout.T)
print("Error in hidden layer's output, Error_at_hidden_layer:\n")
print(Error_at_hidden_layer)

Error in hidden layer's output, Error_at_hidden_layer:

[[ 0.00035638  0.00095186  0.00063856]
 [ 0.00028115  0.00075092  0.00050375]
 [-0.00262878 -0.0070212  -0.00471019]]


In [31]:
#Step 9
d_hiddenlayer = Error_at_hidden_layer * Slope_hidden_layer
print("Delta of hidden layer, d_hiddenlayer:\n")
print(d_hiddenlayer)

Delta of hidden layer, d_hiddenlayer:

[[ 2.96095379e-05  1.81344382e-04  7.85149634e-05]
 [ 1.30136379e-05  7.95519253e-05  4.88802507e-05]
 [-3.09673716e-04 -8.57731275e-04 -6.90698194e-04]]


In [34]:
#Step 10: Update weight at both output and hidden layer
wout = wout + np.dot(np.transpose(hiddenlayer_activations), d_output) * learning_rate
wh = wh+ np.dot(np.transpose(X), d_hiddenlayer) * learning_rate
print("New Output layer weight, wout:\n")
print(wout)
print("New Hidden layer weight, wh:\n") 
print(wh)

New Output layer weight, wout:

[[0.30131665]
 [0.80749936]
 [0.54128248]]
New Hidden layer weight, wh:

[[0.59695396 0.77027807 0.81852177]
 [0.19564817 0.73085806 0.60531449]
 [0.72649173 0.1541627  0.36268941]
 [0.6769297  0.92165951 0.31598834]]


In [37]:
#Step 11: Update biases at both output and hidden layer
bh = bh + np.sum(d_hiddenlayer, axis=0) * learning_rate
bout = bout + np.sum(d_output, axis=0) * learning_rate
print("New Hidden layer bias, bh:") 
print(bh)
print("New Output layer bias, bout:")
print(bout)

New Hidden layer bias, bh:
[[0.97260738 0.14184263 0.60465777]]
New Output layer bias, bout:
[[0.69348944]]
