[View in Colaboratory](https://colab.research.google.com/github/rohithmanjunath/mlblr_assignment2/blob/master/Manjunath_D_Batch6_Assignment2b.ipynb)

In [3]:
import numpy as np

#sigmoid
def sigmoid(x):
  return (1/(1+np.exp(-x)))

def derivatives_sigmoid(x):
  return (x*(1-x))
  
def random_init(size, low=0.0, high=1.0):
  return np.random.uniform(size=size, low=low, high=high)

learning_rate = 0.1

#Step 0
X = np.array([[1,0,1,0],[1,0,1,1],[0,1,0,1]])
y = np.array([[1],[1],[0]])

#Step 1
wh = random_init((4,3))
bh = random_init((1,3))
wout = random_init((3,1))
bout = random_init((1,1))

print("Input, X:\n")
print(X)
print("Target Output, y:\n")
print(y)
print("Hidden layer weight, wh:\n")
print(wh)
print("Hidden layer bias, bh:\n")
print(bh)
print("Output layer weight, wout:\n")
print(wout)
print("Hidden layer bias, bout:\n")
print(bout)



Input, X:

[[1 0 1 0]
 [1 0 1 1]
 [0 1 0 1]]
Target Output, y:

[[1]
 [1]
 [0]]
Hidden layer weight, wh:

[[0.06986834 0.8004591  0.49682602]
 [0.50860743 0.06273843 0.64738292]
 [0.18340584 0.21715629 0.48427051]
 [0.59631657 0.07779371 0.40413068]]
Hidden layer bias, bh:

[[0.81551923 0.17184849 0.71255831]]
Output layer weight, wout:

[[0.43658294]
 [0.96572261]
 [0.48935072]]
Hidden layer bias, bout:

[[0.17946371]]


In [4]:
#Step 2
hidden_layer_input = np.dot(X, wh) + bh
print("Hidden layer input, hidden_layer_input:\n")
print(hidden_layer_input)

Hidden layer input, hidden_layer_input:

[[1.06879341 1.18946388 1.69365484]
 [1.66510998 1.26725759 2.09778551]
 [1.92044322 0.31238063 1.76407191]]
