[View in Colaboratory](https://colab.research.google.com/github/rohithmanjunath/mlblr_assignment2/blob/master/Manjunath_D_Batch6_Assignment2b.ipynb)

In [2]:
import numpy as np

#sigmoid
def sigmoid(x):
  return (1/(1+np.exp(-x)))

def derivatives_sigmoid(x):
  return (x*(1-x))
  
def random_init(size, low=0.0, high=1.0):
  return np.random.uniform(size=size, low=low, high=high)

learning_rate = 0.1

#Step 0
X = np.array([[1,0,1,0],[1,0,1,1],[0,1,0,1]])
y = np.array([[1],[1],[0]])

#Step 1
wh = random_init((4,3))
bh = random_init((1,3))
wout = random_init((3,1))
bout = random_init((1,1))

print("Input, X:\n")
print(X)
print("Target Output, y:\n")
print(y)
print("Hidden layer weight, wh:\n")
print(wh)
print("Hidden layer bias, bh:\n")
print(bh)
print("Output layer weight, wout:\n")
print(wout)
print("Hidden layer bias, bout:\n")
print(bout)



Input, X:

[[1 0 1 0]
 [1 0 1 1]
 [0 1 0 1]]
Target Output, y:

[[1]
 [1]
 [0]]
Hidden layer weight, wh:

[[0.10384061 0.99592364 0.41427757]
 [0.55001171 0.46159552 0.55099996]
 [0.78672944 0.31091351 0.67968617]
 [0.46893092 0.50471785 0.33637801]]
Hidden layer bias, bh:

[[0.6159282  0.76642111 0.71499275]]
Output layer weight, wout:

[[0.0333872 ]
 [0.19314587]
 [0.5371915 ]]
Hidden layer bias, bout:

[[0.58583441]]
